Traceback (most recent call last):
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/portalocker.py", line 398, in lock
    self.locker(fd, flags)
OSError: [Errno 9] Bad file descriptor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/home/aandreev/evo_network/scripts/comparing_to_exact_solution/exact_sat_watts_strogatz_uniform_1-2_uniform_0_75-1_40_8_0_5_123.py", line 10, in <module>
    from src.tss import TSSProblem
  File "/nfs/home/aandreev/evo_network/src/tss.py", line 5, in <module>
    from pysat.pb import EncType
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/pysat/__init__.py", line 97, in <module>
    params = _params.Parameters()
             ^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/pysat/_params.py", line 149, in __init__
    with Lock(self.file_path, 'r', timeout=10) as fout:
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/utils.py", line 316, in __enter__
    return self.acquire()
           ^^^^^^^^^^^^^^
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/utils.py", line 307, in acquire
    raise exception
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/utils.py", line 284, in acquire
    fh = self._get_lock(fh)
         ^^^^^^^^^^^^^^^^^^
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/utils.py", line 341, in _get_lock
    portalocker.lock(fh, self.flags)
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/portalocker.py", line 441, in lock
    _posix_locker_instance.lock(file, flags)
  File "/nfs/home/aandreev/evo_network/evo_network/lib/python3.12/site-packages/portalocker/portalocker.py", line 407, in lock
    raise exceptions.LockException(
portalocker.exceptions.LockException: [Errno 9] Bad file descriptor
